### ISSUE TITLE
Better error handle from spawning next build

### ISSUE THREAD

**Issue by khuezy** [serverless-stack/open-next#69] opened 2023-04-05 18:09 UTC
```typescript
function buildNextjsApp(packager: "npm" | "yarn" | "pnpm") {
  cp.spawnSync(packager, packager === "npm" ? ["run", "build"] : ["build"], {
    stdio: "inherit",
    cwd: appPath,
  });
}
```

open-next should capture any errors and output it to the console.

eg:
```typescript
const spawn =  cp.spawnSync(packager, packager === "npm" ? ["run", "build"] : ["build"], {
    stdio: "inherit",
    cwd: appPath,
  });

if (spawn.stderr) {
  console.log(Error(spawn.stderr))
  process.exitCode = 1;
}
```

**Comment by GinIsTheAnswer** [comment] 2023-04-06 16:28
I can confirm that the issue is what @edvinerikson pointed out. Manually adding the .cmd to packager solves the build.

It also doesn't spit out spawn.stderr, but rahter spawn.error.

**Comment by fwang** [comment] 2023-04-06 22:56
Fixed in v0.8.2

**Closed by fwang** 2023-04-06 22:56 UTC
